<?php

//Auto-generated by ArtaxServiceBuilder - https://github.com/Danack/ArtaxServiceBuilder
//
//Do not be surprised when any changes to this file are over-written.
//
namespace FlickrService;

interface FlickrAPI {

    /**
     * GetOauthRequestToken
     *
     * Starts the Oauth process.
     *
     * @param mixed $oauth_callback The URL that an authorisation request should return
     * the user to.
     * @return \FlickrService\Operation\GetOauthRequestToken The new operation
     */
    public function GetOauthRequestToken($oauth_callback);

    /**
     * GetOauthAccessToken
     *
     * Exchanges Oauth request token for access token.
     *
     * @param mixed $oauth_verifier The oauth_verifier that shows that the user was
     * redirected back to your site.
     * @return \FlickrService\Operation\GetOauthAccessToken The new operation
     */
    public function GetOauthAccessToken($oauth_verifier);

    /**
     * UploadPhoto
     *
     * Uploads a photo.
     *
     * @param mixed $photo The file to upload
     * @param mixed $title The title of the photo.
     * @param mixed $description The description of the photo
     * @param mixed $tags A space-separated list of tags to apply to the photo.
     * @param mixed $async Whether to process the file asynchronously.
     * @return \FlickrService\Operation\UploadPhoto The new operation
     */
    public function UploadPhoto($photo, $title, $description, $tags, $async);

    /**
     * flickr.people.getPhotos
     *
     * Return photos from the given user's photostream. Only photos visible to the
     * calling user will be returned. This method must be authenticated; to return
     * public photos for a user, use <a
     * href="/services/api/flickr.people.getPublicPhotos.html">flickr.people.getPublicPhotos</a>.
     *
     * @param mixed $user_id Which user to get the photos of
     * @return \FlickrService\Operation\flickrPeopleGetPhotos The new operation
     */
    public function flickrPeopleGetPhotos($user_id);

    /**
     * flickr.people.getPhotosOf
     *
     * Returns a list of photos containing a particular Flickr member.
     *
     * @param mixed $user_id todo - describe variable
     * @return \FlickrService\Operation\flickrPeopleGetPhotosOf The new operation
     */
    public function flickrPeopleGetPhotosOf($user_id);

    /**
     * flickr.people.getPublicPhotos
     *
     * Get a list of public photos for the given user.
     *
     * @param mixed $user_id Which user to get the photos of
     * @return \FlickrService\Operation\flickrPeopleGetPublicPhotos The new operation
     */
    public function flickrPeopleGetPublicPhotos($user_id);

    /**
     * flickr.test.login
     *
     * A testing method which checks if the caller is logged in then returns their
     * username.
     *
     * @return \FlickrService\Operation\flickrTestLogin The new operation
     */
    public function flickrTestLogin();

    /**
     * executeAsync
     *
     * Execute an operation asynchronously.
     *
     * @param \ArtaxServiceBuilder\Operation $operation The operation to perform
     * @param callable $callback The callback to call on completion/response. The
     * signature of the method should be:
     * function(
     *     \Exception $error = null, // null if no error 
     *     $parsedData = null, //The parsed operation data i.e. same type as
     * responseClass of the operation.
     *     \Amp\Artax\Response $response = null //The response received or null if the
     * request completely failed.
     * )
     * @return \Amp\Promise A promise to resolve the call at some time.
     */
    public function executeAsync(\Amp\Artax\Request $request, \ArtaxServiceBuilder\Operation $operation, callable $callback);


}
